data:
  batch_size: 256
  num_workers: 6
  seed: ${train.seed}
  dataset:
    train_image_path: '/data/yuto/datasets/coco/train2017'
    train_json: '/data/yuto/datasets/coco/annotations/captions_train2017.json'
    val_image_path: '/data/yuto/datasets/coco/val2017'
    val_json: '/data/yuto/datasets/coco/annotations/captions_val2017.json'

train:
  start_epoch: 0
  epochs: 30
  warmup_epochs: 2
  lr: null
  base_lr: 1e-3
  weight_decay: 0.05
  warmup_lr: 4e-6
  min_lr: 4e-5
  clip_grad: 0.1
  accumulation_steps: 0
  amp_opt_level: O1
  seed: 0

  lr_scheduler:
    # name: cosine
    patience: 1
    factor: 0.8

  optimizer:
    name: adamw
    eps: 1e-8
    betas: [0.9, 0.999]

model:
  image:
    encoder:
      name: 'vit'
      size: 224
      patch_size: 14
      embeddings: 512
  text:
    encoder:
      name: 'distilbert-base-uncased' 
      pretrained: true
      trainable: false
      embeddings: 768
  clip:
    projection: 256
    dropout: 0.1
    temperature: 1
  mae:
    mask_ratio: 0.75
  loss:
    alpha: 1

checkpoint:
  auto_resume: true
  resume: ''
  freq: 1
  max_kept: -1
  save_freq: 1

model_name: '' # display name in the logger
test: false
output: './tmp'
tag: default
print_freq: 10
seed: 0
wandb: false
local_rank: ???
vis: []
device: 'cuda'
world_size: 4
